### ISSUE TITLE
Any authenticated call yields to `ret_code: 10001`

### ISSUE THREAD

**Issue by pansen** [bybit-exchange/docs#321]
**Bug Description**
I'm trying to cover basic operations with the testnet API. For that purpose I created testnet API keys and a simple test. This test is configured to use [`vcrpy`](https://vcrpy.readthedocs.io/en/latest/), so we have a wonderful record to look at. 

The test looks like this: 

```python
@vcr.use_cassette()
@pytest.mark.asyncio()
async def test_successful_buy_order(bybit_client: bybit):
    """
    From the documentation https://bybit-exchange.github.io/docs/inverse_futures/#t-getactive
    ```
    curl "https://api.bybit.com/futures/private/order/list?api_key={api_key}&timestamp={timestamp}&sign={sign}&symbol=BTCUSDM21"
    ```
    
    We create: 
    ```
    https://api-testnet.bybit.com/futures/private/order/list?symbol=BTCUSDT&timestamp=1636453918288&api_key=cO5...&sign=...
    ```
    """
    time_res = bybit_client.Common.Common_getTime().result()
    assert 0 == time_res[0]['ret_code']

    # https://www.bybit.com/data/basic/linear/contract-detail?symbol=BTCUSDT
    symbol = 'BTCUSDM21'

    # Docs: https://bybit-exchange.github.io/docs/inverse_futures/#t-placeactive
    open_orders_before: Tuple[dict, dict] = bybit_client.FuturesOrder\
        .FuturesOrder_getOrders(symbol=symbol)\
        .result()
    assert 0 == open_orders_before[0]['ret_code']
    assert 'error' not in open_orders_before[0]['ret_msg'].lower()
```

The created vcrpy *cassette* (record of requests) looks like: 

```yaml
interactions:
- request:
    body: null
    headers:
      Accept:
      - '*/*'
      Accept-Encoding:
      - gzip, deflate
      Connection:
      - keep-alive
      User-Agent:
      - Official-SDKs
    method: GET
    uri: https://api-testnet.bybit.com/v2/public/time?timestamp=1636454072717&api_key=cO5...&sign=...
  response:
    body:
      string: '{"ret_code":0,"ret_msg":"OK","ext_code":"","ext_info":"","result":{},"time_now":"1636454074.031054"}'
    headers:
      Cache-Control:
      - max-age=0, no-cache, no-store
      Connection:
      - keep-alive
      Content-Length:
      - '100'
      Content-Type:
      - application/json; charset=utf-8
      Date:
      - Tue, 09 Nov 2021 10:34:34 GMT
      Expires:
      - Tue, 09 Nov 2021 10:34:34 GMT
      Pragma:
      - no-cache
    status:
      code: 200
      message: OK
- request:
    body: null
    headers:
      Accept:
      - '*/*'
      Accept-Encoding:
      - gzip, deflate
      Connection:
      - keep-alive
      User-Agent:
      - Official-SDKs
    method: GET
    uri: https://api-testnet.bybit.com/futures/private/order/list?symbol=BTCUSDM21&timestamp=1636454073043&api_key=cO5...&sign=...
  response:
    body:
      string: '{"ret_code":10001,"ret_msg":"params error!","ext_code":"","ext_info":"","result":null,"time_now":"1636454074.375736"}'
    headers:
      Cache-Control:
      - max-age=0, no-cache, no-store
      Connection:
      - keep-alive
      Content-Length:
      - '117'
      Content-Type:
      - application/json; charset=utf-8
      Date:
      - Tue, 09 Nov 2021 10:34:34 GMT
      Expires:
      - Tue, 09 Nov 2021 10:34:34 GMT
      Pragma:
      - no-cache
    status:
      code: 200
      message: OK
version: 1
```

To me, this looks like exactly as in the documentation, unfortunately I have no idea why I'm receiving this error-code. 

**Browser (please complete the following information):**
 - OS: [macOS Big Sur]
 - bybit 0.2.12
 - ```
    $ .venv/bin/python -V
    Python 3.9.7
    ```

**Comment by pansen** [comment]
The problem also happens on production. I created another test, which is not spending money, using the production API. 

```python
@vcr.use_cassette()
@pytest.mark.asyncio()
async def test_cancel_all(bybit_client: bybit):
    """cancel all open orders"""

    # curl https://api.bybit.com/futures/private/order/cancelAll \
    #     -H "Content-Type: application/json" \
    #     -d '{"api_key":"{api_key}","symbol":"BTCUSDM21","timestamp":{timestamp},"sign":"{sign}"}'
    time_res = bybit_client.Common.Common_getTime().result()
    assert 0 == time_res[0]['ret_code']

    # https://www.bybit.com/data/basic/linear/contract-detail?symbol=BTCUSDT
    symbol = 'BTCUSDT'
    cancel_all_res: Tuple[dict, dict] = bybit_client.FuturesOrder\
        .FuturesOrder_cancelAll(symbol=symbol)\
        .result()
    assert 0 == cancel_all_res[0]['ret_code']
    assert 'error' not in cancel_all_res[0]['ret_msg'].lower()
```

Getting

```yaml
interactions:
- request:
    body: null
    headers:
      Accept:
      - '*/*'
      Accept-Encoding:
      - gzip, deflate
      Connection:
      - keep-alive
      User-Agent:
      - Official-SDKs
    method: GET
    uri: https://api.bybit.com/v2/public/time?timestamp=1636470033376&api_key=5z...&sign=...
  response:
    body:
      string: '{"ret_code":0,"ret_msg":"OK","ext_code":"","ext_info":"","result":{},"time_now":"1636470034.934235"}'
    headers:
      Cache-Control:
      - max-age=0, no-cache, no-store
      Connection:
      - keep-alive
      Content-Length:
      - '100'
      Content-Type:
      - application/json; charset=utf-8
      Date:
      - Tue, 09 Nov 2021 15:00:35 GMT
      Expires:
      - Tue, 09 Nov 2021 15:00:35 GMT
      Pragma:
      - no-cache
    status:
      code: 200
      message: OK
- request:
    body: symbol=BTCUSDT
    headers:
      Accept:
      - '*/*'
      Accept-Encoding:
      - gzip, deflate
      Connection:
      - keep-alive
      Content-Length:
      - '14'
      Content-Type:
      - application/x-www-form-urlencoded
      User-Agent:
      - Official-SDKs
    method: POST
    uri: https://api.bybit.com/futures/private/order/cancelAll?timestamp=1636470034037&api_key=5z...&symbol=BTCUSDT&sign=...
  response:
    body:
      string: '{"ret_code":10001,"ret_msg":"params error!","ext_code":"","ext_info":"","result":null,"time_now":"1636470035.349015"}'
    headers:
      Cache-Control:
      - max-age=0, no-cache, no-store
      Connection:
      - keep-alive
      Content-Length:
      - '117'
      Content-Type:
      - application/json; charset=utf-8
      Date:
      - Tue, 09 Nov 2021 15:00:35 GMT
      Expires:
      - Tue, 09 Nov 2021 15:00:35 GMT
      Pragma:
      - no-cache
    status:
      code: 200
      message: OK
version: 1
```
